name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint (Readability)
        run: npx eslint . --ext .js,.mjs

      - name: Run Prettier (Maintainability)
        run: npx prettier --check "**/*.js"

      - name: Run Jest (Coverage)
        run: npx jest --coverage

      - name: Run Stryker (Mutation Testing)
        run: npx stryker run

      - name: Run Performance Tests
        run: node performance.js

      - name: Fix Permissions
        run: sudo chmod -R 755 node_modules/.bin
      

     
      
