name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint (Readability)
        run: npx eslint . --ext .js,.mjs

      - name: Run Prettier (Maintainability)
        run: npx prettier --check "**/*.js"

      - name: Run Jest (Coverage)
        run: npx jest --coverage

      - name: Run Stryker (Mutation Testing)
        run: npx stryker run

      - name: Run Performance Tests
        run: node performance.js

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2  # Use v3 if working, else fallback to v2
        with:
          name: coverage-report
          path: coverage/

      - name: Upload Stryker Mutation Report
        uses: actions/upload-artifact@v2
        with:
          name: mutation-report
          path: reports/

      
